insert into seccion values(10000, 'DE', 'Lácteos');
insert into seccion values(20000, 'DE', 'Frutas y verduras');
insert into seccion values(30000, 'DE', 'Carnes y pescados');
insert into seccion values(40000, 'DE', 'Salchichonería');
insert into seccion values(50000, 'DE', 'Cervezas, vinos y licores');
insert into seccion values(60000, 'DE', 'Farmacia');
insert into seccion values(70000, 'DE', 'Bebés');

insert into seccion values(80000, 'TH', 'Pantallas');
insert into seccion values(90000, 'TH', 'Computadoras');
insert into seccion values(100000, 'TH', 'Electrodomésticos');
insert into seccion values(110000, 'TH', 'Celulares');

insert into producto values(10001, 10000, 19.80, 400, 'Leche Alpura Clásica entera 1 L', 'La leche entera es primordial en tu lista de abarrotes ya que es una fuente de vitaminas y proteínas que puedes incluir en las mañanas para tener una alimentación balanceada. La leche Alpura Clásica, en su presentación de 1 litro adicionada con vitaminas A y D que son esenciales para tener una buena salud y un sistema inmunológico fuerte, puede formar parte de una alimentación balanceada porque es un producto lácteo muy nutritivo. ');
insert into producto values(10001, 10000, 16.90, 390, 'Leche Yaqui entera 1 L', 'Encuentra en Ksi-Mart en línea la clásica presentación de leche entera de 1 litro, con ella complementas un desayuno completo ya que se recomienda consumir alimentos lácteos con regularidad, puedes preparar licuados con fruta de temporada y granola o chocolate, es un ingrediente básico que no debe faltar en tu despensa.');
insert into producto values(10002, 10000, 20.50, 370, 'Leche Santa Clara entera 1 L', 'La leche entera Santa Clara es pura de vaca adicionada con calcio y vitamina A que fortalecen los huesos y ayudan a mantener saludable la vista. Este producto lácteo no debe faltar en tu lista de abarrotes porque se puede usar para desayunos nutritivos de muchas formas: ya sea que prepares unos hot cakes, un licuado de frutas naturales o simplemente tomes un vaso con leche fría, puedes contar con el delicioso sabor de la leche Santa Clara de 1 litro.');
insert into producto values(10003, 10000, 16.00, 420, 'Producto lácteo Nutri Leche 1 L', 'NutriLeche® con su delicioso sabor contribuye a la nutrición de tus hijos lo cual es muy importante si consideramos que una buena nutrición les ayuda a lograr más cada día. Añadiendo en tu lista de productos NutriLeche® en su presentación de 1 litro, adicionada con vitamina A, D, B1, B2, B5 y hierro, llevarás sabor y nutrición a tu hogar.');
insert into producto values(10004, 10000, 20.90, 500, 'Leche Lala entera 1 L', 'La Leche Lala Entera® es ideal para iniciar tu día con la mejor actitud, dado que te brinda nutrimentos y energía vitales para tu cuerpo. Inclúyela en la despensa del hogar, ya que es ideal para un estilo de vida activo. Consiente a los pequeños de la casa con un vaso de esta deliciosa leche y ten un desayuno agradable con tu familia.');
insert into producto values(10005, 10000, 14.40, 340, 'Producto lácteo Forti Leche 7 Plus 1 L', 'Consumir lácteos es muy importante en la dieta diaria por su contenido de calcio; además, algunos de ellos están adicionados con vitaminas y minerales que complementan una sana alimentación. La fórmula láctea de Fortileche, en su presentación de 1 litro, cuenta con un valor nutricional agregado porque viene enriquecida con vitamina A, B6,D, ácido fólico, niacina y hierro; además pueden hacerse ricos batidos con las frutas de temporada que complementarán la alimentación diaria.');
insert into producto values(10006, 10000, 16.90, 410, 'Leche Great Value entera 1 L', 'Si estás buscando alimentos ricos en calcio, tenemos para ti un producto lácteo que te encantará. Llévate la leche entera de la marca Great Value que tenemos en presentación de 1 litro y disfruta de este alimento rico en calcio que además es delicioso. Disfruta todos los beneficios de la leche natural en un rico vaso de leche por las mañanas o a cualquier hora del día. ');
insert into producto values(10007, 10000, 18.00, 290, 'Leche San Marcos entera 1 L', 'Incluye en tu lista de lácteos la leche entera San Marcos, con propiedades como vitaminas A y D, ideales para el desayuno saludable de toda la familia. Logra una alimentación balanceada sin perder el rico sabor y cremosidad de tu leche favorita. Los productos lácteos de San Marcos son ideales para integrar en tu despensa básica, ya que cuentan con una gran variedad de lácteos y derivados que podrás combinar con fruta, café o pastas. ');