insert into seccion values(10000, 'DE', 'Lácteos');
insert into seccion values(20000, 'DE', 'Frutas y verduras');
insert into seccion values(30000, 'DE', 'Carnes y pescados');
insert into seccion values(40000, 'DE', 'Salchichonería');
insert into seccion values(50000, 'DE', 'Cervezas, vinos y licores');
insert into seccion values(60000, 'DE', 'Farmacia');
insert into seccion values(70000, 'DE', 'Bebés');

insert into seccion values(80000, 'TH', 'Pantallas');
insert into seccion values(90000, 'TH', 'Computadoras');
insert into seccion values(100000, 'TH', 'Electrodomésticos');
insert into seccion values(110000, 'TH', 'Celulares');


insert into producto values(10001, 10000, 19.80, 400, 'Leche Alpura Clásica entera 1 L', 'La leche entera es primordial en tu lista de abarrotes ya que es una fuente de vitaminas y proteínas que puedes incluir en las mañanas para tener una alimentación balanceada. La leche Alpura Clásica, en su presentación de 1 litro adicionada con vitaminas A y D que son esenciales para tener una buena salud y un sistema inmunológico fuerte, puede formar parte de una alimentación balanceada porque es un producto lácteo muy nutritivo. ');
insert into producto values(10002, 10000, 16.90, 390, 'Leche Yaqui entera 1 L', 'Encuentra en Ksi-Mart en línea la clásica presentación de leche entera de 1 litro, con ella complementas un desayuno completo ya que se recomienda consumir alimentos lácteos con regularidad, puedes preparar licuados con fruta de temporada y granola o chocolate, es un ingrediente básico que no debe faltar en tu despensa.');
insert into producto values(10003, 10000, 20.50, 370, 'Leche Santa Clara entera 1 L', 'La leche entera Santa Clara es pura de vaca adicionada con calcio y vitamina A que fortalecen los huesos y ayudan a mantener saludable la vista. Este producto lácteo no debe faltar en tu lista de abarrotes porque se puede usar para desayunos nutritivos de muchas formas: ya sea que prepares unos hot cakes, un licuado de frutas naturales o simplemente tomes un vaso con leche fría, puedes contar con el delicioso sabor de la leche Santa Clara de 1 litro.');
insert into producto values(10004, 10000, 16.00, 420, 'Producto lácteo Nutri Leche 1 L', 'NutriLeche® con su delicioso sabor contribuye a la nutrición de tus hijos lo cual es muy importante si consideramos que una buena nutrición les ayuda a lograr más cada día. Añadiendo en tu lista de productos NutriLeche® en su presentación de 1 litro, adicionada con vitamina A, D, B1, B2, B5 y hierro, llevarás sabor y nutrición a tu hogar.');
insert into producto values(10005, 10000, 20.90, 500, 'Leche Lala entera 1 L', 'La Leche Lala Entera® es ideal para iniciar tu día con la mejor actitud, dado que te brinda nutrimentos y energía vitales para tu cuerpo. Inclúyela en la despensa del hogar, ya que es ideal para un estilo de vida activo. Consiente a los pequeños de la casa con un vaso de esta deliciosa leche y ten un desayuno agradable con tu familia.');
insert into producto values(10006, 10000, 14.40, 340, 'Producto lácteo Forti Leche 7 Plus 1 L', 'Consumir lácteos es muy importante en la dieta diaria por su contenido de calcio; además, algunos de ellos están adicionados con vitaminas y minerales que complementan una sana alimentación. La fórmula láctea de Fortileche, en su presentación de 1 litro, cuenta con un valor nutricional agregado porque viene enriquecida con vitamina A, B6,D, ácido fólico, niacina y hierro; además pueden hacerse ricos batidos con las frutas de temporada que complementarán la alimentación diaria.');
insert into producto values(10007, 10000, 16.90, 410, 'Leche Great Value entera 1 L', 'Si estás buscando alimentos ricos en calcio, tenemos para ti un producto lácteo que te encantará. Llévate la leche entera de la marca Great Value que tenemos en presentación de 1 litro y disfruta de este alimento rico en calcio que además es delicioso. Disfruta todos los beneficios de la leche natural en un rico vaso de leche por las mañanas o a cualquier hora del día. ');
insert into producto values(10008, 10000, 18.00, 290, 'Leche San Marcos entera 1 L', 'Incluye en tu lista de lácteos la leche entera San Marcos, con propiedades como vitaminas A y D, ideales para el desayuno saludable de toda la familia. Logra una alimentación balanceada sin perder el rico sabor y cremosidad de tu leche favorita. Los productos lácteos de San Marcos son ideales para integrar en tu despensa básica, ya que cuentan con una gran variedad de lácteos y derivados que podrás combinar con fruta, café o pastas. ');



insert into producto values(20001, 20000, 28.90, 50, 'Plátano macho por kilo', 'En Ksi-Mart tienda en línea tenemos para ti el nutritivo plátano macho, sin duda una fruta típica que no puede faltar en los hogares. Este alimento está lleno de beneficios para tu salud, contiene fibra, vitaminas para la piel, es fuente de potasio para los huesos y controla la hipertensión. Puedes comerlo todos los días para que goces de una buena salud, recuerda disfrutarlo sobretodo cocinado. Hornéalo o prepáralo con muy poco aceite, perfecto para postres como plátanos fritos con leche condensada o para acompañar el plato fuerte. ');
insert into producto values(20002, 20000, 19.90, 90, 'Plátano Chamitos orgánico por kilo', 'El plátano orgánico por kilo es un producto perfecto para disfrutar a lado de tu familia ya sea en platillos de cocina como arroz con plátano, postres como el pay de plátano o simplemente disfrutar una pieza del increíble sabor que un producto orgánico te brinda, ya que gracias a su cosecha libre de pesticidas posee un sabor único. No olvides comprar todos los ingredientes que necesitas para poder preparar platillos naturales y saludables para tu familia.');
insert into producto values(20003, 20000, 69.00, 40, 'Nectarina por kilo', 'Dale a tu familia productos naturales, frescos y con un delicioso sabor, adquiere en Ksi-Mart tienda en línea y cómela sola o disfrútala en conserva, jalea, mermelada o en confitura, sin duda es el postre perfecto y nutritivo que a todos encantará. Además esta fruta cuenta con múltiples propiedades benéficas para la salud, contiene vitaminas A, B3, C y ácido fólico, que contribuyen a la producción de colágeno, un componente muy importante para la piel; también ayuda a reducir los niveles de colesterol, por sus nutrientes es ideal para incluirla en tu dieta diaria.');
insert into producto values(20004, 20000, 84.00, 40, 'Uva blanca sin semilla por kilo', 'En Ksi-Mart tienda en línea nos gusta que lleves una vida sana y nutritiva, por eso traemos para ti la uva blanca sin semilla. Una fruta fresca que debe estar incluida en tu dieta diaria pues aporta múltiples beneficios a tu organismo. Las uvas tienen diferentes propiedades que favorecen a la salud pues ayudan a prevenir el cáncer, lesiones arteriales y neurológicas; tienen un alto contenido en vitaminas C, K, y B6. Puedes comerlas solas o en ensaladas con algunos otros complementos que aporten más nutrientes a tu cuerpo. ');
insert into producto values(20005, 20000, 24.90, 60, 'Melón chino por kilo', 'Si quieres preparar un delicioso coctel de frutas, en Ksi-Mart tenemos para ti los productos más frescos y de gran calidad, como el melón chino que te brinda un sabor dulce y es ideal para integrar en tu dieta diaria gracias a sus propiedades nutrimentales. Contiene grandes cantidades de vitamina C que te ayuda a hidratar tu piel evitando imperfecciones y protege tu sistema inmunológico. Además, es un excelente diurético que limpia tu sistema digestivo y elimina la acidez provocada por el exceso de grasas, así que no dudes en llevarlo a tu mesa y disfrutarlo a la hora que quieras. ');
insert into producto values(20006, 20000, 59.00, 70, 'Manzana granny smith por kg', 'Una fruta fresca con un sabor ácido es la granny Smith. Descubre la experiencia que esta manzana crujiente la despensa de tu hogar. Son muy buenas para preparar cualquier tipo de receta de cocina incluyendo los platillos para hornear. No lo pienses más y crea incluso un puré. Esta manzana es alta en fibra y antioxidantes además de ser baja en calorías y grasas, son aptas para una buena alimentación. Pruébala. ');
insert into producto values(20007, 20000, 75.00, 80, 'Limón eureka por kilo', 'Refréscate de manera natural con una deliciosa agua con chía, pepino y limón eureka, que a diferencia del limón tradicional, tiene un sabor menos agrio y por su esencia también es muy útil para que los agregues en guisos o postres. Este tipo de cítricos son ricos en vitamina C, la cual te ayuda a prevenir enfermedades respiratorias, además fortalece tu sistema inmunológico y contrarresta la presencia de bacterias en tu cuerpo. ');
insert into producto values(20008, 20000, 17.90, 60, 'Mandarina por kilo', 'Una de las frutas de temporada más esperadas son las mandarinas, ya que de entre las frutas y verduras, son las que tienen un elevado contenido de vitamina C además de ser un cítrico de sabor dulce y delicado. Consume jugo de mandarina como un antigripal natural y prepárate para esta época decembrina en la que las defensas deben estar altas con la ayuda de esta fruta fresca. ');
insert into producto values(20009, 20000, 14.90, 70, 'Naranja valencia por kilo', 'Comenzar el día con un vaso de jugo es casi una tradición en muchos hogares, pues las propiedades de los cítricos son incuestionables. Por ello, la Naranja Valencia es un alimento que siempre debes tener a la mano. Además, pese a que comúnmente se sirve de este modo, su uso puede aportarte una gran cantidad de soluciones también al momento de cocinar.La Naranja Valencia cuenta con propiedades nutricionales que le permiten ayudar a contrarrestar problemas que van desde trastornos estomacales o dolor de cabeza hasta estrés y depresión. Además de su alto contenido de vitamina C, posee minerales como calcio, fósforo, hierro y magnesio. Por si fuera poco, con ella puedes eliminar bacterias y dar un sabor más agradable a alimentos como el pollo o el pato, entre muchos otros.');

insert into producto values(20010, 20000, 96.00, 50, 'Pimiento naranja por kg', 'Condimenta con un sabor especial tus guisados con carne, pues con el pimiento naranja puedes hacer gran variedad de recetas ya que le otorga un sabor fuerte y un toque dulce, además de aportarle una buena fuente de nutrientes y vitaminas y lo mejor es que contiene pocas calorías, selecciona los kilos que necesites y surte toda tu despensa en Ksi-Mart en línea.');
insert into producto values(20011, 20000, 39.90, 60, 'Coliflor por pieza', 'Sorprende a tu familia al cocinar platillos ricos y sanos con la variedad de vegetales que tenemos para ti, como la coliflor que tenemos disponible por pieza en Ksi-Mart tienda en línea a un buen precio y prepárala a la parmesana, al pesto, al bechamel o capeada, descubre la innumerable cantidad de recetas que puedes elaborar con esta verdura. Conoce también sus propiedades nutritivas, pues se trata de un alimento rico en vitaminas B6 y K, al igual que en proteínas, ácido fólico, fósforo y potasio que mejoran la salud del corazón y del cerebro, también es benéfica para la digestión. Ahora que conoces sus cualidades no esperes más para incluirla en tu alimentación.');
insert into producto values(20012, 20000, 16.90, 170, 'Elote amarillo por pieza', 'El maíz o elote es el único cereal con betacaroteno que aporta fibras, hidratos de carbono y vitaminas del grupo B, además reduce el colesterol alto. Prepáralo con arroz blanco, atún, o como esquites hervidos con mayonesa, queso rallado y chile piquín, disfruta de este ya tradicional alimento.');
insert into producto values(20013, 20000, 54.00, 120, 'Camote morado por kilo', 'Cuando se trata de variar las opciones con que cuentas para alimentar a tu familia, las vainas y tubérculos son algo que siempre debes tener en mente. El Camote morado, que pertenece a esta clasificación, es un producto cuyas propiedades y rico sabor te sacarán de muchos apuros al momento de preparar tus comidas, mientras que, al mismo tiempo, brindará a tu organismo nutrientes al por mayor. Entre los beneficios de consumir esta variedad de vainas y tubérculos, destaca su aporte para retrasar el envejecimiento, así como su contribución a que la hipertensión disminuya. Lo anterior es posible gracias a su alto contenido de vitaminas C y A. Prepáralo al carbón, horneado o hasta en puré, y disfruta en cada versión un sabor único y muy agradable, que no querrás dejar de probar.');
insert into producto values(20014, 20000, 120.00, 50, 'Chile habanero por kilo', 'Prepara esos platillos que más le gustan a tu familia solo con productos de alta calidad, como el chile habanero que añade a tus comidas ese toque picante que todos les encanta. Adquiérelo por kilo en la tienda en línea de Ksi-Mart y disfruta de hacer tus compras por internet. Los chiles habaneros son fáciles de cocinar, combínalos con un poco de cebolla morada, jugo de limón y trozos de piña para aminorar el picor, sazona con sal al gusto. Una combinación perfecta para acompañar una carne asada, o platillos típicos como cochinita pibil. El consumo de chile habanero ayuda a la aceleración del metabolismo, alivia dolores musculares y reduce el colesterol en la sangre.');
insert into producto values(20015, 20000, 18.90, 70, 'Lechuga italiana por pieza', 'La lechuga italiana posee un valor nutricional destacado, es una de la plantas comestibles más utilizadas en la cocina su sabor es más fuerte y su textura crujiente; además posee propiedades antioxidantes, diuréticas y fortalece el sistema nervioso. Otro de los beneficios de la lechuga más conocidos es como ayuda para conciliar el sueño ya que contiene lactucina, lo que tranquiliza los nervios, como recomendación, realizar un infusión con sus hojas sería la mejor manera de consumirla y poder descansar. ');
insert into producto values(20016, 20000, 31.90, 130, 'Cebolla amarilla por kilo', 'Complementa tu despensa del día con las cebollas amarillas, adquiérelas a través de Ksi-Mart tienda en línea y prepara deliciosos platillos como sopas, asados de carnes, salsas y estofados, su sabor fuerte es perfecto para resaltar tus recetas de cocina favoritas. Se caracterizan por poseer propiedades nutritivas que benefician al cuerpo, son ricas en vitaminas A, B, C y E, en minerales y oligoelementos que ayudan a prevenir la diabetes, además favorecen al sistema circulatorio y son eficaces contra problemas respiratorios; sin duda son ideales para incluirlas como parte de una alimentación saludable.');
insert into producto values(20017, 20000, 120.00, 40, 'Ajo japonés 80 g', 'En Ksi-Mart tienda en línea te ofrecemos un amplio surtido de semillas importadas que ayudan a regular los niveles de colesterol malo en el organismo. Adquiere a un buen precio el ajo, el cual es un gran aliado para las personas que padecen diabetes ya que disminuye la glucosa en la sangre. Este tipo de ajo actúa de forma inmediata para mantener bajos los triglicéridos, así como el ácido úrico. Para las personas que buscan mantener una vida más saludable, es recomendable comer una pieza en ayunas para obtener una buena digestión y mejorar el metabolismo.');
insert into producto values(20018, 20000, 48.90, 150, 'Aguacate hass por kilo', 'Sin lugar a dudas, uno de los alimentos básicos de la comida mexicana es el Aguacate Hass, por lo que es un ingrediente que no debe faltar en tu hogar. Seguramente este es un producto que consumes regularmente en una gran variedad de salsas o como acompañamiento de carnes o ensaladas, pero al conocer los beneficios que aporta a tu organismo, querrás hacerlo aún más a menudo. El Aguacate Hass es una fruta con una gran cantidad de nutrientes, entre los que destaca su alto contenido de vitamina E y fibra. Su consumo ayuda a disminuir los niveles de colesterol, así como a regular la presión arterial. Además, su textura y sabor lo convierten en un alimento que se adapta fácilmente a muchos platillos de otras cocinas del mundo.');
insert into producto values(20019, 20000, 39.90, 140, 'Jitomate bola gourmet por kilo', 'Jitomate bola gourmet por kg.');
insert into producto values(20020, 20000, 59.00, 90, 'Espárrago Altar verde por pza', 'Los espárragos son una gran fuente de nutrientes, por eso es muy bueno que formen parte de tu lista de vegetales habituales ya que fortalecen el cuerpo por su alto contenido de fibra y ácido fólico. Consumir estas verduras verdes te ayudará a tener una piel sana y una mejor digestión. Puedes encontrar todos tus alimentos frescos como frutas y verduras haciendo tu despensa en línea. ');
insert into producto values(20021, 20000, 86.00, 80, 'Alcachofa por pieza', 'La alcachofa es una hortaliza de gran sabor que además de servir como alimento contiene una gran cantidad de propiedades antioxidantes, así como las vitaminas y minerales que tu cuerpo necesita. Cómprala en la tienda en línea de Ksi-Mart a un precio increíble. Es una excelente aliada para la digestión, para bajar de peso y para la eliminación de líquidos. Con ella puedes preparar deliciosos platillos, ya sea al horno, asadas, fritas, en salsa, o incluso alcachofas rellenas de carne, queso o verduras. ');
insert into producto values(20022, 20000, 39.90, 90, 'Berenjena por kilo', 'Prepara una comida práctica, fácil y saludable con las berenjenas de excelente calidad que tenemos para ti. Adquiérelas desde la comodidad de tu hogar, saca el chef que llevas dentro y prepara con ellas increíbles platillos. Esta verdura es rica en vitamina C y E, nutrientes que funcionan como antioxidante para el cuerpo, ayudan a mejorar la circulación de la sangre y contribuyen a reducir los niveles altos de colesterol, por lo que es recomendable consumirlas frecuentemente. Utilízalas para hacer jugos, ensaladas, para acompañar algunos cortes de carne o prepararlas asadas y degustarlas con hojas de laurel.');



insert into producto values(30001, 30000, 405.00, 50, 'Lomo de res centro por kg', 'El lomo de res es un elemento muy esencial en las recetas de cocina mexicana ya que suele combinarse con múltiples verduras y prepararse ya sea frita, en caldo o acompañada de una guarnición; se considera un alimento rico en proteínas que según como sea combinado puede representar una comida completa que nutra a tu familia de forma práctica y en un solo guisado. Recuerda que consumir carne de res de vez en cuando es una opción de alimentación saludable ya que repone las proteínas que utilizamos todos los días en los músculos.');
insert into producto values(30002, 30000, 65.00, 210, 'Pierna y muslo de pollo sin piel por kg', 'Si no sabes qué hacer de comer prepara una deliciosa receta de pollo ya que es uno de los alimentos ricos en proteínas más popular en México. La pierna y el muslo de este animal tienen un muy buen precio y se pueden preparar en infinidad de guisados por su gran sabor. ');
insert into producto values(30003, 30000, 88.00, 120, 'Pierna de cerdo sin hueso entera por kg', 'La pierna de cerdo es muy fácil de cocinar, por lo que no tendrás que pasar horas en la cocina; para estas fechas te sugerimos prepararla en adobo o salsa de ciruela y acompañar con alguna guarnición. ¡Degusta un delicioso platillo de una manera sencilla! Todo lo que necesites para consentir a los tuyos lo encuentras en Ksi-Mart en línea a precios siempre bajos, además contamos con servicio a domicilio para tu comodidad.');
insert into producto values(30004, 30000, 90.00, 110, 'Chuleta de cerdo por kg', 'No pases horas en la cocina preparando la comida, si no tienes tiempo ¡no te preocupes! Compra chuleta de cerdo, su sabor es rico y es fácil de cocinar. Sólo pon un poco de aceite en una sartén y déjalo calentar, mete la chuleta de cerdo y déjala cocer. Cuando esté lista, retírala del fuego y absorbe el exceso de grasa con una servilleta y ¡eso es todo, está lista para servir! Acompaña tu platillo con papas a la francesa o con una ensalada con lechuga al gusto, pepino, zanahoria y jícama. Si quieres darle un poco más de sabor a la carne, añade algún tipo de salsa como verde o roja. Sin duda, una comida saludable y deliciosa.');
insert into producto values(30005, 30000, 94.00, 90, 'Milanesa de cerdo por kg', 'La milanesa de cerdo proviene de la pierna de cerdo y es un elemento que puede ser la parte principal de tus recetas de comida, ya que es rica en proteínas y vitaminas. Prepárala al natural, marinada, empanizada, horneada, frita o al sartén y sírvele a tu familia una comida completa. Mantenla en refrigeración de 0 a 4 °C. ');
insert into producto values(30006, 30000, 234.00, 110, 'Fajitas de ternera por kg', 'No pases horas en la cocina, prepara un delicioso platillo fácil de cocinar que te tomará poco tiempo. Las fajitas de ternera son perfectas para consentir a tu familia y sus beneficios nutrimentales son múltiples, ya que es un alimento bajo en grasas y muy fácil de digerir por su alto contenido de agua. Además una de sus características principales es su ternura, lo que la hace fácil de masticar. Para preparar unas deliciosas fajitas de ternera lo único que necesitas es pimiento rojo, pimiento verde, cebolla y un poco de queso rallado. Pon todos los ingredientes en una sartén a fuego medio y déjalos cocer, cuando veas que están en su punto agrega queso al gusto. Calienta tortillas de harina o maíz ¡y listo para servir! Puedes acompañarlas con diferentes salsas que resaltarán su sabor. ');
insert into producto values(30007, 30000, 232.00, 90, 'Falda de res por kg', 'Falda de res por kg. Surte lista de despensa y crea diferentes recetas de cocina mexicana, a tu familia le encantará, recuerda que tus compras en línea desde Ksi-Mart.com.mx cuentan con entrega a domicilio.');
insert into producto values(30008, 30000, 189.00, 130, 'Huachinango del golfo chico por kg', 'Llévate este fresco y delicioso huachinango del golfo chico por pieza y disfrútalo en un día caluroso acompañado de una bebida fría, imaginando que estás comiendo este pez a la orilla de la playa. En Ksi-Mart tienda en línea encuentras variedades de pescados y complementos para su total preparación. No dejes de disfrutar el gran sabor y la gran frescura de su carne blanca. Existen muchas recetas para este pez como el famoso pescado zarandeado o el pescado a la veracruzana. Se pueden cocinar en horno, a las brasas, empanizados, capeados y en cualquier otra forma que se te ocurra. Además de su sabor el huachinango es bajo en calorías, rico en proteínas, posee vitaminas del grupo B, su carne es de fácil digestión y favorece a una buena circulación.');
insert into producto values(30009, 30000, 85.00, 110, 'Pescado para caldo congelado por kg', 'Una dieta saludable que cuente con una variedad de alimentos y la cantidad suficiente de proteínas, te proporciona las reservas de nutrientes que necesitas para conservar energía durante tu día. Elige el mejor artículo en Ksi-Mart tienda online como el pescado congelado para caldo por kilogramo. El pescado es rico en calcio, vitaminas, complejo B y Omega 3. Ideal para preparar en caldo, una receta sencilla, nutritiva y muy saludable, perfecta para servir en épocas de frío, que es cuando más apetece tomar algo caliente.');
insert into producto values(30010, 30000, 99.00, 90, 'Pescado Sierra entera por kg', 'Degusta el delicioso sabor del pez sierra que Ksi-Mart trae para ti, puedes cocinarlo en filetes fritos, en escabeche en un delicioso ceviche o como mas lo prefieras, encuentra una gran variedad de pescados y mariscos en Ksi-Mart.com.mx y comparte su delicioso sabor con tus seres queridos.');
insert into producto values(30011, 30000, 67.00, 80, 'Mojarra mexicana por kg', 'Disfruta de los nutrientes que te ofrece el consumo de pescado con la mojarra mexicana por kilo que se encuentra disponible en tu tienda en línea Ksi-Mart. Con este alimento fresco puedes elaborar una amplia variedad de recetas de comida, descubre su sabor y complementa con una mezcla de verduras hervidas o ensalada fresca.');
insert into producto values(30012, 30000, 79.00, 180, 'Barrita de pescado empanizado por kg', 'No te compliques la existencia a la hora de preparar la comida, en Ksi-Mart tienda en línea te damos las mejores opciones para una comida rica, saludable y súper fácil. Como estas barritas de pescado empanizado por kilogramo, una alternativa muy agradable con todos los nutrientes que caracterizan este alimento. Estos dedos de pescado son la solución para esos días en que no tienes tiempo de cocinar, cuenta con propiedades nutricionales excelentes como proteínas, vitaminas B1, B2, B3, minerales como el sodio y el hierro, son bajos en grasa y su sabor les encantará a tus hijos. Acompaña con una ensalada de lechuga o verduras al vapor.');
insert into producto values(30013, 30000, 79.00, 190, 'Figuritas de pescado empanizadas por kg', 'Lleva toda la diversión y al mismo tiempo la nutrición que te brindan estas figuritas de pescado empanizadas por kg que tenemos para ti y tu familia en Ksi-Mart tienda en línea. Sin duda un alimento especial para los más pequeños de tu hogar. Haz que la hora de la comida sea más divertida y saludable. El pescado es considerado un alimento básico dentro de una alimentación saludable, y se recomienda comer de dos a cuatro raciones de pescado por semana. Los beneficios que aporta son proteínas para formar y mantener los órganos y tejidos de nuestro organismo, aportan muy pocas calorías, es rico en sodio y omega 3.');



insert into producto values(40001, 40000, 18.45, 90, 'Mix de semillas Green Mountain omega 3 60 g', 'Mix de semillas Green Mountain omega 3, 60 g. Ya puedes hacer tus compras en línea desde la comodidad de tu hogar en Ksi-Mart.com.mx y recibir tu despensa a domicilio completa con tan solo unos cuantos clics desde tu celular o computadora.');
insert into producto values(40002, 40000, 48.00, 120, 'Aceitunas Busta verdes enteras con hueso 440 g', 'Aceitunas Busta verdes enteras con hueso 440 g.');
insert into producto values(40003, 40000, 65.00, 90, 'Pepitas Calidad Selecta fritas 200 g', 'Comparte en tus reuniones unas deliciosas pepitas y consiente a tus invitados con este producto, En Ksi-Mart.com.mx encontrarás una gran variedad de productos nutritivos para tu despensa básica. Haz tus compras y aprovecha las ofertas de martes de frescura que tu tienda en línea tiene para ti.');
insert into producto values(40004, 40000, 58.00, 100, 'Queso Oaxaca Lala reducido en grasa 400 g', 'Si buscas preparar unas enchiladas suizas o disfrutar de un delicioso queso derretido en algún platillo mexicano, puedes utilizar queso Oaxaca Lala® Light ya que se presta para gratinarse y cuenta con un excelente sabor. El queso Oaxaca Lala® Light además de tener el excelente sabor que lo caracteriza, está reducido en grasa, lo que te permite hacerlo parte de tu dieta.');
insert into producto values(40005, 40000, 49.00, 100, 'Queso panela Lala 400 g', 'El Queso Panela Lala® está muy presente en la comida mexicana, es fresco y de consistencia suave. El Queso Panela Lala® tiene un sabor único. Además de su consistencia única y sabor ligeramente salado, el queso panela es ideal si disfrutas de cuidar tu alimentación por su menor contenido calorico, comparado con otros quesos. Es ideal para acompañar unas ricas enchiladas verdes, sándwiches y tus platillos favoritos. Queso Panela Lala® en su presentación de 400 gr, ideal para compartir en familia. ');
insert into producto values(40006, 40000, 61.00, 100, 'Queso cotija Del Parral rallado 300 g', 'El queso cotija rallado Del Parra es perfecto para utilizarlo en diferentes recetas de la gastronomía mexicana. No dejes pasar la oportunidad de probar su sabor en cada creación que se te ocurra. Deleita a tus seres queridos con tus comidas. El queso está hecho con leche entera de vaca, por ello cuenta con un sabor fuerte. Conviértelo en tu aliado en la cocina. ');
insert into producto values(40007, 40000, 65.00, 100, 'Queso fresco Covadonga burgos 400 g', 'Queso burgos Covadonga 400 g, hecho con leche fresca 100% de vaca. Realiza tu despensa en línea en la página de Ksi-Mart.com.mx y recibe todo lo que solicitas en las puertas de tu hogar gracias al excelente servicio que te ofrecemos.');
insert into producto values(40008, 40000, 122.00, 100, 'Queso chihuahua Montebello 1 kg', 'El queso chihuahua puede ser utilizado en infinidad de recetas de comida, ya que es un elemento ideal para preparar platillos gratinados, como botana o como parte central de un guisado. Esto se debe a que su sabor y consistencia deleitan el paladar de todo el que lo pruebe y le dan un toque especial a tus comidas. El queso Chihuahua Montebello nos presenta una pieza de 1kg y no puede faltar en tu despensa básica, ya que es un excelente derivado de la leche, que además de tener un delicioso sabor, se derrite muy fácilmente para que prepares tus comidas favoritas. ');



insert into producto values(50001, 50000, 169.00, 40, 'Cerveza clara Corona Extra 12 botellas de 355 ml c/u', 'Cerveza Corona es la cerveza de origen 100% mexicano más vendida en el mundo. Su origen data de 1925, y hoy en día está presente en más de 120 países, solo producida en México, y dedicada a promover lo mejor de nuestra cultura mexicana en el mundo. De estilo Mexican Lager, es una cerveza clara, color dorado, muy ligera y refrescante. Esta presentación de Corona Extra en botella 12 pack de 355ml es ideal para disfrutar junto con tus seres queridos en una fiesta o reunión y con cualquier platillo de mariscos y pescados. Contiene 4.5% de nivel de alcohol. ');
insert into producto values(50002, 50000, 169.00, 50, 'Cerveza oscura Victoria 12 botellas de 355 ml c/u', 'La cerveza oscura Victoria, ofrece un sabor exquisito y refrescante. Ideal para acompañar con diferentes tipos de platillos. Es una cerveza premium tipo lager y con estilo Vienna, color oscuro. Cuenta con un cuerpo medio y su espuma es cremosa. Creada en el año de 1865 convirtiéndola en una de las cervezas más antiguas de México. Disfruta de su sabor ligeramente dulce a lado de tus familiares y amigos, deleita tus sentidos. Ideal para fiestas y reuniones.');
insert into producto values(50003, 50000, 168.00, 70, 'Cerveza clara Tecate light 12 latas de 355 ml c/u', 'La cerveza es una de las bebidas alcohólicas más habituales en las fiestas ya que tiene un bajo porcentaje de alcohol y hay para muchos gustos. Con el 12 pack de cerveza Tecate light, podrás amenizar tus celebraciones en la compañía de tus seres queridos y pasar grandes momentos; ya que esta presentación alcanza para todos.');
insert into producto values(50004, 50000, 179.00, 120, 'Vino espumoso Zonin Prosecco doc 750 ml', 'Agrega a tu cava de vinos las diferentes bebidas alcohólicas que tenemos para ti, como el vino espumoso Zonin doc que tenemos en presentación de 750 ml. Este vino de mesa, por el tipo de uva con el que está hecho tiene un intenso aroma muy afrutado con perfume de flores blancas y manzanas dulces, es el aperitivo por excelencia y perfecto para acompañar con pescados, risottos y cremas. Consiente a tus invitados, familiares o amigos en cualquier ocasión con este sabor tan especial del vino espumoso Zonin doc.');
insert into producto values(50005, 50000, 159.00, 110, 'Vino blanco Santa Rita 120 sauvignon blanc 750 ml', 'Para esa comida en familia, no dejes de llevar bebidas para disfrutar y compartir, como el vino blanco Santa Rita sauvignon blanc que tenemos en presentación de 750 ml. En este vino de mesa, por el tipo de uva con el que está hecho, destacan aromas de frutos tropicales, principalmente cítricos como la lima y piel de limón y algunas notas de durazno.');
insert into producto values(50006, 50000, 145.00, 130, 'Vino rosado Sutter Home white zinfandel 750 ml', 'El vino rosado Sutter Home White Zinfandel se elabora en los viñedos de Napa, California, y cuenta con un color salmón brillante además, como su nombre lo menciona, está elaborado con el tipo de uva zinfandel, en nariz es frutal, con aroma a limón amarillo, fresas, melón, manzana, pera, durazno e higo. Tiene cuerpo balanceado y armónico con sabor seco y una fina suavidad cremosa. Es una excelente opción para marinar con pescados, mariscos, ensaladas frescas, sushi, pastas, pizza, quesos de sabor medio y gazpacho. Utilízalo como vino de mesa, no te arrepentirás. ');
insert into producto values(50007, 50000, 315.00, 90, 'Tequila Jose Cuervo Tradicional reposado 950 ml', 'Invita a tus amigos las mejores bebidas preparadas con tequila reposado, como el tradicional charro negro que tendrá un toque especial con el tequila José Cuervo. Encuéntralo en su presentación de 950 ml, contiene un 38% de volumen de alcohol y es extraído 100% del agave azul. Ideal para disfrutarlo solo o en cualquier combinación. ');
insert into producto values(50008, 50000, 499.00, 120, 'Tequila Don Julio reposado 750 ml', 'El tequila Don Julio es una bebida tradicional en nuestro país, y con la gran variedad de sus presentaciones como: tequila añejo, tequila blanco y más, podrás preparar diferentes cocteles con alcohol y disfrutar de su característico sabor. Te presentamos el tequila reposado Don Julio con un 38% de alcohol. Este tequila se destila en alambiques de cobre en pequeños lotes y es madurado durante 8 meses. Su color ámbar dorado con notas de chocolate, vainilla y frutas maduras, es ideal para degustarlo solo o acompañado. Su final es sedoso y cálido con esencias de frutas secas, nueces y un toque de manzana caramelizada. ');
insert into producto values(50009, 50000, 385.00, 120, 'Whiskey Jack Daniels Honey 700 ml', 'Jack Daniel´s Honey en busca de romper esquemas y de agregar a la tradición un toque de originalidad, tiene para ti a través de Ksi-Mart tienda en línea la botella de 750 ml, una edición que incluye miel natural. Mézclalo con un poco de ginger o bien solo en las rocas. Encuentra las diferentes marcas de whisky que tenemos disponibles para ti, como esté whisky Jack Daniels en presentación de 700 ml. No dejes de tener diferentes tipos de vinos y disfruta cuando lo desees.');



insert into producto values(60001, 60000, 20.00, 110, 'Toallitas húmedas Kotex para limpieza íntima 20 pzas', 'Toallitas húmedas Kotex para limpieza íntima 20 piezas.');
insert into producto values(60002, 60000, 32.50, 50, 'Talco desodorante Olorex con triclosán mentol 200 g', 'Talco desodorante Olorex con triclosán mentol 200 g. Haz tus compras en línea sin salir de casa en Ksi-Mart.com.mx y recibe tus productos favoritos en las puertas de tu casa con tan solo unos cuantos clics desde tu celular, tablet o computadora. ');
insert into producto values(60003, 60000, 48.60, 30, 'Desenfriol D 2 mg/ 5 mg/ 500 mg 24 tabletas', 'Desenfriol D 2 mg/ 5 mg/ 500 mg 24 tabletas. En nuestro departamento de Farmacia podrás encontrar los medicamentos que necesitas, además de artículos de curación, botiquines, suplementos, entre muchos otros.');
insert into producto values(60004, 60000, 126.00, 40, 'Theraflu TD resfriado común y dolor de cabeza sabor limón 10 sobres', 'Auxiliar en el alivio de los síntomas del resfriado común y dolor de cabeza, como: reducción temporal de fiebre y escalofríos, dolores musculares, congestión nasal y de senos paranasales. Sabor Limón');
insert into producto values(60005, 60000, 30.50, 50, 'Jabón de tocador Asepxia exfoliante extremo 100 g', 'Recomendado para la piel mixta. Exfolia y limpia tu piel a profundidad, mientras ayuda a combatir imperfecciones y puntos negros. Su nueva fórmula Hidro-Force ayuda a disminuir el exceso de grasa, destapando los poros a profundidad. Potencializado con 2% de ácido salicílico y esferas de jojoba. ');
insert into producto values(60006, 60000, 54.50, 30, 'Silka Medic gel 15 g', 'Gel indicado para el tratamiento del pie de atleta y las infecciones micóticas de la piel ubicadas en íngles, manos, tórax y axilas. ');
insert into producto values(60007, 60000, 145.00, 45, 'Condones Playboy mix & play 10 pzas', 'Mix and Play 10 pzas. Lata porta condones contiene: 10 condones (5 texturizados y 5 extra sensibles). Largo: 190 mm +/-10mm. Ancho: 52 mm +/- 2mm. Espesor: 0.07 mm +/-0.02mm y 0.06 mm +/-0.02mm. Color: látex natural. Material: hule látex natural lubricados con receptáculo. Probados electrónicamente. Tecnología 100% alemana. Sticker coleccionable de regalo');
insert into producto values(60008, 60000, 55.00, 60, 'Condones Sico Ultrasense 3 pzas', 'Los condones Sico® Invisible están hechos de hule látex con receptáculo, extra delgados, de paredes rectas, transparente y con lubricante de silicón que te permiten sentirte más cerca de tu pareja. Diseñados de forma anatómica que te permiten fácil colocación y mayor sensación. Auxiliar en la prevención del embarazo, ayuda a reducir el riesgo de contagio por VIH/SIDA y otras infecciones transmitidas sexualmente. ');
insert into producto values(60009, 60000, 140.00, 70, 'Condones Trojan Piel Desnuda 9 pzas', 'Condones Trojan Piel Desnuda, 40 % más delgado, lubricante premium, ultra suave, hule látex natural, bajo olor a látex.');



insert into producto values(70001, 70000, 337.00, 40, 'Pañales Huggies UltraConfort etapa 5 niña 60 pzas', 'Huggies UltraConfort es el único pañal que brinda total libertad de movimiento para un mejor desarrollo psicomotriz de tu bebé. Su cubierta interna Ultra Suave le permite a tu bebé moverse sin irritaciones y sin fricción. Su cubierta interna tiene una mejor absorbencia gracias a su centro texturizado que distribuye los líquidos, está adicionada con Aloe, Manzanilla y Vitamina E. Los pañales Huggies UltraConfort tienen cintas elásticas que acompañan a tu bebé en todos sus movimientos y no permiten que nada le estorbe. Mantienen la piel seca y fresca ya que permiten que el aire pase gracias a su cubierta externa respirable. Recomendado para bebés de 12 a 14 kg. ');
insert into producto values(70002, 70000, 15.00, 210, 'Papilla Gerber etapa 3 verduras con pollo y arroz 170 g', 'Las papillas 3ERA. ETAPA® de GERBER® te apoyarán para llegar a la transición a la dieta familiar, fomentando buenos hábitos alimenticios. Contiene más variedades con textura más espesa, para que tu bebé aprenda a masticar. Además, están fortificadas con vitamina C, hierro y zinc para ayudar al crecimiento de tu bebé.');
insert into producto values(70003, 70000, 24.00, 50, 'Agua Gerber 4 L', 'Agua Gerber, formulada por el experto en nutrición infantil, cuenta con un balance de minerales especialmente diseñado para tu bebé que es suave con su estomaguito ya que facilita la absorción de los nutrientes de sus alimentos');
insert into producto values(70004, 70000, 12.50, 180, 'Avena Nestlé Nestum a partir de 6 meses 90 g', 'Los cereales NESTUM® son el inicio ideal de los alimentos sólidos de los bebés ya que contienen gran cantidad de vitaminas y minerales con 50% DEL HIERRO que necesita al día, en una porción pequeña para su estomaguito además NO CONTIENE AZUCAR AÑADIDA. Iniciar con NESTUM® ayuda a que los bebés se incorporen poco a poco a los sólidos gracias a que su preparación es con leche materna y además debido a su proceso de producción son de fácil digestión.');
insert into producto values(70005, 70000, 69.00, 120, 'Talco para bebés Mennen baby magic hipoalergénico rosa 500 g', 'No esperes que tu bebé tenga algún tipo de rozadura en la piel, aplica talco Mennen Baby Magic de 500 gramos. El talco Mennen protege la piel de tu hijo, por ser un producto hipoalergénico lo hace más seguro e impide que tu hijo tenga reacciones alérgicas después de aplicarlo. Descubre todos los productos que Mennen ofrece para el cuidado de tu bebé y siéntete tranquila de la calidad que los respalda. ');
insert into producto values(70006, 70000, 53.00, 150, 'Toallitas húmedas Depend 42 pzas', 'Las Toallas Húmedas Depend no contienen alcohol y son hipoalergénicas. Cada toalla mide 23 x 21.6 cm, lo que facilitará la limpieza del familiar o el paciente. Son de gran tamaño para proteger toda la mano. Las toallas cuentan con una textura doble; por un lado son lisas para brindar suavidad, mientras que por el lado acolchado ofrecen mayor limpieza. Encuéntralas disponibles en una práctica presentación con 42 toallas húmedas tamaño extra grande, que facilitarán la rutina de higiene diaria de tu paciente o familiar y podrán acompañarte para cualquier emergencia. ');
insert into producto values(70007, 70000, 21.50, 80, 'Shampoo Ricitos de Oro manzanilla 100 ml', 'Consiente al pequeño del hogar con el shampoo Ricitos de Oro manzanilla hipoalergénico con suave aroma, que además de brindar una limpieza completa del cabello delicado de tu pequeño, lo aclara y lo acondiciona durante su uso. Un artículo de higiene que no debe de faltar en los productos para tu bebé. ');
insert into producto values(70008, 70000, 199.00, 60, 'Pañales Huggies Supreme etapa 2 unisex 38 pzas', 'Con Huggies Supreme tu bebé contará con lo más avanzado en cuidado y protección para mantener saludable su delicada piel. El pañal se ajusta suave y delicadamente a las piernas y gracias al extracto de algodón, evita las marcas rojas. Su tecnología de absorción encapsula el PH de la orina, además, cuenta con una banda elástica que ayuda a disminuir escurrimientos por la espalda. La cubierta interna 3Dermo Protect evita que la materia fecal semi líquida, entre en contacto con la piel y protege su delicada piel ya que está adicionada con Aloe, Manzanilla, Vitamina E y Avena Protec. También permite que la piel de tu bebé respire y se mantenga seca y fresca gracias a su cubierta externa respirable con extracto de algodón. Recomendado para bebés de 5 a 7.5 kg.');

